config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :albums
  resources :songs
  resources :artists
  
  get root to: 'homepage#index'
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, :released_at, :cover_art_url, :length, :kind, presence:true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, :permalink, :bio, :formed_at, :verified_at, :avatar_url, :cover_photo_url, presence:true
end

app/models/song.rb
class Song < ApplicationRecord
  validates :url, :name, :credits, presence:true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :set_album, only: [:edit, :update, :destroy]
    def index
        @albums = Album.all
    end

    def new
        @album = Album.new
    end

    def create
        @album = Album.new(album_params)

        if @album.save
            flash[:notice] = "A new album has been added"
            redirect_to albums_path
        else
            flash[:error] = "There are some errors encountered"
            render :new
        end
    end

    def edit
        @album = Album.find(params[:id])
    end

    def update

        if @album.update(album_params)
            redirect_to albums_path
        else
            render :edit
        end
    end

    def destroy
        @album.destroy
        redirect_to albums_path, notice: "The album was successfully deleted"
    end

    private 
    
    def set_album
        @album = Album.find(params[:id])
    end

    def album_params
        params.require(:album).permit(:name, :released, :released_at, :cover_art_url, :length, :kind)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:edit, :update, :destroy]
  def index
      @artists = Artist.all
  end

  def new
      @artist = Artist.new
  end

  def create
      @artist = Artist.new(artist_params)

      if @artist.save
          flash[:notice] = "A new artist has been added"
          redirect_to artists_path
      else
          flash[:error] = "There are some errors encountered"
          render :new
      end
  end

  def edit
      @artist = Artist.find(params[:id])
  end

  def update

      if @artist.update(artist_params)
          redirect_to artists_path
      else
          render :edit
      end
  end

  def destroy
      @artist.destroy
      redirect_to artists_path, notice: "The artist was successfully deleted"
  end

  private

  def set_artist
      @artist = Artist.find(params[:id])
  end

  def artist_params
      params.require(:artist).permit(:name, :permalink, :bio, :formed_at, :verified, :verified_at, :avatar_url, :cover_photo_url, )
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index 

  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:edit, :update, :destroy]
  def index
      @songs = Song.all
  end

  def new
      @song = Song.new
  end

  def create
      @song = Song.new(song_params)

      if @song.save
          flash[:notice] = "A new track has been added"
          redirect_to songs_path
      else
          flash[:error] = "There are some errors encountered"
          render :new
      end
  end

  def edit
      @song = Song.find(params[:id])
  end

  def update
      song_params = params.require(:song).permit(:url, :name, :credits)

      if @song.update(song_params)
          redirect_to songs_path
      else 
          render :edit
      end
  end

  def destroy
      @song.destroy
      redirect_to songs_path, notice: "The song was successfully deleted"
  end

  private

  def set_song
      @song = Song.find(params[:id])
  end

  def song_params
      params.require(:song).permit(:url, :name, :credits)
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/edit.html.haml
= form_with model: @album do |f|
  = f.label :name
  = f.text_field :name

  %br/

  = f.label :released_at
  = f.date_field :released_at

  %br/
  = f.label :cover_art_url
  = f.url_field :cover_art_url

  %br/

  = f.label :length
  = f.time_select :length, {:ampm => false}

  %br/
  
  = f.label :kind
  = f.radio_button :kind, 'Single'
  = label :kind_single, 'Single'
  = f.radio_button :kind, 'EP'
  = label :kind_EP, 'EP'
  = f.radio_button :kind, 'LP'
  = label :kind_EP, 'LP' 

  %br/  

  = f.submit
  
  %br/
  = link_to "Back to Albums", albums_path

app/views/albums/index.html.haml
%h1 Albums

%table
  %thread
    %th Name
    %th Released at
    %th Cover Art URL 
    %th Length
    %th Kind
  
  %tbody
    - @albums.each do |album|
      %tr
        %td
          = album.name
        %td
          = album.released_at
        %td
          = album.cover_art_url.truncate(150)
        %td
          = album.length 
        %td
          = album.kind
        %td
          = link_to "Edit", edit_album_path(album.id)
          = link_to "Delete", album_path(album.id), method: :delete, data: {confirm: "Are you sure?"}

%br/
= link_to "Add Albums", new_album_path        

%br/
= link_to "Go to Artists", artists_path

%br/
= link_to "Go to Tracks", songs_path

%br/
= link_to "Back to Home", root_path

app/views/albums/new.html.haml
= form_with model: @album do |f|
  = f.label :name
  = f.text_field :name

  %br/

  = f.label :released_at
  = f.date_field :released_at

  %br/
  = f.label :cover_art_url
  = f.url_field :cover_art_url

  %br/

  = f.label :length
  = f.time_select :length, {:ampm => false}

  %br/

  = f.label :kind
  = f.radio_button :kind, 'Single'
  = label :kind_single, 'Single'
  = f.radio_button :kind, 'EP'
  = label :kind_EP, 'EP'
  = f.radio_button :kind, 'LP'
  = label :kind_EP, 'LP' 

  %br/  

  = f.submit
  
  %br/
  = link_to "Back to Albums", albums_path

app/views/artists/edit.html.haml
= form_with model: @artist do |f|
  = f.label :name
  = f.text_field :name
  %br/

  = f.label :permalink
  = f.text_field :permalink
  
  %br/
  = f.label :bio
  = f.text_area :bio

  %br/

  = f.label :formed_at
  = f.date_field :formed_at

  %br/

  = f.label :verified_at
  = f.date_field :verified_at

  %br/

  = f.label :avatar_url
  = f.url_field :avatar_url


  %br/

  = f.label :cover_photo_url
  = f.url_field :cover_photo_url

  %br/

  = f.submit
  
  %br/
  = link_to "Back to Artists", artists_path

app/views/artists/index.html.haml
%h1 Artists

%table
  %thread
    %th Name
    %th Permalink
    %th Bio
    %th Formed at
    %th Verified at
    %th Avatar URL 
    %th Cover photo URL

%tbody
  - @artists.each do |artist|
    %tr
      %td
        = artist.name
      %td
        = artist.permalink
      %td
        = artist.bio.truncate(150)
      %td
        = artist.formed_at
      %td
        = artist.verified_at 
      %td
        = artist.avatar_url
      %td
        = artist.cover_photo_url
      %td
        = link_to "Edit", edit_artist_path(artist.id)
        = link_to "Delete", artist_path(artist.id), method: :delete, data: {confirm: "Are you sure?"}

%br/
= link_to "Add Artist", new_artist_path

%br/
= link_to "Go to Albums", albums_path

%br/
= link_to "Go to Tracks", songs_path

%br/
= link_to " Back to Home", root_path

app/views/artists/new.html.haml
= form_with model: @artist do |f|
  = f.label :name
  = f.text_field :name
  %br/

  = f.label :permalink
  = f.text_field :permalink
  
  %br/
  = f.label :bio
  = f.text_area :bio

  %br/

  = f.label :formed_at
  = f.date_field :formed_at

  %br/

  = f.label :verified_at
  = f.date_field :verified_at

  %br/

  = f.label :avatar_url
  = f.url_field :avatar_url


  %br/

  = f.label :cover_photo_url
  = f.url_field :cover_photo_url

  %br/

  = f.submit
  
  %br/
  = link_to "Back to Artists", artists_path

app/views/homepage/index.html.haml
%h1 HOMEPAGE HERE

%br/
= link_to "Artists", artists_path

%br/
= link_to "Albums", albums_path

%br/
= link_to "Tracks", songs_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.haml
= form_with model: @song do |s|
  = s.label :url
  = s.url_field :url
  
  %br/
  = s.label :name
  = s.text_field :name

  %br/

  = s.label :credits
  = s.text_area :credits

  %br/

  = s.submit
  
  %br/
  = link_to "Back to Songs", songs_path
  

app/views/songs/index.html.haml
%h1 Songs

%table
  %thread
    %th url
    %th Name
    %th Credits 
    %th Available
  
  %tbody
    - @songs.each do |song|
      %tr
        %td
          = song.url.truncate(150)
        %td
          = song.name
        %td
          = song.credits.truncate(150)
        %td
          = song.available
        %td
          = link_to "Edit", edit_song_path(song.id)
          = link_to "Delete", song_path(song.id), method: :delete, data: {confirm: "Are you sure?"}

%br/
= link_to "Add Songs", new_song_path        

%br/
= link_to "Go to Artists", artists_path

%br/
= link_to "Go to Albums", albums_path

%br/
= link_to "Back to Home", root_path

app/views/songs/new.html.haml
= form_with model: @song do |s|
  = s.label :url
  = s.url_field :url
  
  %br/
  = s.label :name
  = s.text_field :name

  %br/

  = s.label :credits
  = s.text_area :credits

  %br/

  = s.submit
  
  %br/
  = link_to "Back to Songs", songs_path
  